name: sample_app
description: A new Flutter project

publish_to: 'none' # pub.dev 에 배포하지 않겠다는 의미

version: 0.1.0+1

environment:
  sdk: ^3.6.2 # Dart 버전을 명시

# dependencies: 의존성을 명시
dependencies:
  flutter:
    sdk: flutter
  # flutter 패키지 중 cupertino_icons 의존성을 명시, 애플 아이콘을 사용하기 위함
  cupertino_icons: ^1.0.8 
  # flutter 패키지 중 google_fonts 의존성을 명시, 구글 폰트를 사용하기 위함
  google_fonts: ^6.2.1

# dev_dependencies: 개발용 의존성을 명시
dev_dependencies:
  flutter_test:
    sdk: flutter